os:
  - linux
  - osx
osx_image: xcode10.2
dist: trusty
language: generic
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then eval "$(curl -sL https://swiftenv.fuller.li/install.sh)"; fi
install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then swiftenv install $(cat .swift-version) | grep -qe "\(been\|already\) installed"; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then swift package generate-xcodeproj; fi
script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then travis_wait swift test; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then xcodebuild -project FileLogging.xcodeproj -scheme FileLogging-Package build; fi
